development:
  adapter: postgis
  encoding: unicode
  database: glatos_development
  pool: 5
  username: glatos
  password:
  script_dir: /usr/share/pgsql/contrib/postgis
  schema_search_path: public,postgis

test: &test
  adapter: postgis
  encoding: unicode
  database: glatos_test
  pool: 5
  username: glatos
  password:
  script_dir: /usr/share/pgsql/contrib/postgis
  schema_search_path: public,postgis

staging:
  adapter: postgis
  encoding: unicode
  database: glatos_staging
  port: 5433
  pool: 5
  username: glatos
  password:
  script_dir: /usr/local/pgsql/share/contrib/postgis
  schema_search_path: public,postgis
  template: template0

production:
  adapter: postgis
  encoding: unicode
  database: glatos_production
  port: 5433
  pool: 5
  username: glatos
  password:
  script_dir: /usr/local/pgsql/share/contrib/postgis
  schema_search_path: public,postgis
  template: template0

cucumber:
  <<: *test
